# ENVIRONMENT 
#
# DATE_TIME 2017年6月5日-17时44分48秒
#
# VERSION 1.0.0

# 使用此alpine基础镜像开始构建
FROM registry:2 

# 指定镜像创建者和联系方式
MAINTAINER RyanChang zhd@signit.cn

# 添加外部配置

# 挂载目录
VOLUME ["/var/lib/registry"] 

# 需要暴露端口
EXPOSE 5000