version: '2'
services: 
    mysql:
      hostname: mysql
      image: 114.215.149.118:5000/signit/cloudsign-server-mysql
      #build: /home/s2/mysql-single/Dockerfile
      ports:
           - "3306:3306"  
      volumes:
           - /data/mysql:/var/lib/mysql
      stdin_open: true
